### ISSUE TITLE
Ticketing not centered.

### ISSUE THREAD

**Issue by zkanda** [django/djangoproject.com#379] opened 2015-02-06 09:05 UTC
This is the whole page when viewed in rMBP 13", there's a very large space on the left.

![screen shot 2015-02-06 at 5 00 50 pm](https://cloud.githubusercontent.com/assets/5354184/6076711/ee34154e-ae21-11e4-99ae-61883a61b629.png)

**Comment by bmispelon** [comment] 2015-04-27 17:43
Hi,

Is this issue still present for you? I can't seem to be able to reproduce it.

**Comment by zkanda** [comment] 2015-04-28 01:35
Hi,
I can confirm that I still have this issue, here's the whole screenshot of the browser.
![screen shot 2015-04-28 at 9 31 43 am](https://cloud.githubusercontent.com/assets/5354184/7361359/727f2f04-ed89-11e4-9e73-7a0f5aab10c1.png)

**Comment by bmispelon** [comment] 2015-04-28 08:45
Could you tell us what your screen resolution is?

Thanks.

**Comment by zkanda** [comment] 2015-04-28 09:14
Machine Spec:
Retina MacBook Pro 13",
Native Resolution is 2560 x 1600

But I believe Apple scale this up so that it would look like 1280 x 800
My machine is configured to use the default profile:
![screen shot 2015-04-28 at 5 12 14 pm](https://cloud.githubusercontent.com/assets/5354184/7366286/c3ae4f78-edc9-11e4-856a-d64f94fff844.png)

**Comment by girishkumarkh** [comment] 2015-06-04 15:42
Does this issue belong to https://github.com/django/code.djangoproject.com/issues ?

**Comment by timgraham** [comment] 2015-07-10 13:27
I can reproduce it. It's because the layout uses a centered `max-width: 960px;` container. If the table is wider than that, it overflows on the right.

**Comment by timgraham** [comment] 2015-12-18 17:48
I'm not sure how to resolve this other than to left align the main container in Trac instead of centering it. Something like this in trachacks.css:
```
.full-width [role="main"] {
    float: left;
    margin-left: 25px;
    max-width: 960px;
}
```
Do you think it's an improvement?

**Comment by timgraham** [comment] 2016-07-09 23:04
Closing in absence of other complaints.

**Closed by timgraham** 2016-07-09 23:04 UTC
