### ISSUE TITLE
Badges don't appear on /community/badges/

### ISSUE THREAD

**Issue by shane0** [django/djangoproject.com#735] opened 2017-01-31 22:19 UTC
badges broke for me did they break for you too?

[link](https://www.djangoproject.com/community/badges/)

404 Not Found on [this](https://www.djangoproject.com/s/img/badges/djangopowered126x54.gif)

**Comment by MarkusH** [comment] 2017-01-31 22:48
I can confirm this issue. We're looking into this. This is likely related to https://groups.google.com/forum/#!topic/django-developers/Qyu2wkxPer8

**Comment by timgraham** [comment] 2017-01-31 23:10
Duplicate of https://github.com/django/djangoproject.com/issues/136. The badges were likely copied manually to the old server and need to be checked in to prevent this from happening again. Thanks for the report.

**Closed by timgraham** 2017-01-31 23:10 UTC
Labels: bug

**Comment by shane0** [comment] 2017-02-10 22:35
[thanks for the fix](https://en.wikipedia.org/wiki/Stinking_badges)!
