### ISSUE TITLE
Sitemap URLs include scheme/domain twice

### ISSUE THREAD

**Issue by phodal** [django/djangoproject.com#472] opened 2015-05-25 00:44 UTC
Hi,

   Do you see this sitemap on production of djangoproject.com. we can see a lot of error on [https://www.djangoproject.com/sitemap.xml](https://www.djangoproject.com/sitemap.xml) , I think its some configure error?  We can see domain appear two times.

	<url>
	<loc>
	https://www.djangoproject.comhttps://www.djangoproject.com/weblog/2015/may/22/djangocon-us-registration-open/
	</loc>
	<changefreq>never</changefreq>
	<priority>0.4</priority>
        </url>

**Comment by bmispelon** [comment] 2015-05-25 05:31
Nice catch, thanks.

It appears the problem is also present on the docs sitemap: https://docs.djangoproject.com/sitemap.xml and I wonder if it might be caused by our use of django-hosts.

**Comment by timgraham** [comment] 2015-11-30 22:48
Baptiste, did you mean to send a pull request with those above commits? An alternate approach is provided in https://github.com/django/djangoproject.com/pull/544 but from a quick glance, your fix appears less repetitive.

**Comment by timgraham** [comment] 2015-12-11 18:35
Fixed in 0065b3e443a550cb7a5f80b3ee00f9b2b5cc885c.

**Closed by timgraham** 2015-12-11 18:35 UTC
Labels: bug
