### ISSUE TITLE
Non-even amounts generate a Javascript error

### ISSUE THREAD

**Issue by Xof** [django/djangoproject.com#624] opened 2016-01-14 02:50 UTC
Attempting to donate by including a decimal sign generates a Javascript pop-up error on the page. Screenshot below. The payment is not actually processed.

![screen shot 2016-01-13 at 6 48 46 pm](https://cloud.githubusercontent.com/assets/145915/12314495/6ff02dc8-ba26-11e5-86b3-2d74f86b7826.png)

**Comment by timgraham** [comment] 2016-01-14 11:15
Duplicate of https://github.com/django/djangoproject.com/issues/613

**Closed by timgraham** 2016-01-14 11:15 UTC
