### ISSUE TITLE
New feed approval process is broken

### ISSUE THREAD

**Issue by freakboy3742** [django/djangoproject.com#418] opened 2015-03-26 01:52 UTC
If you try to approve a new feed (either by using the admin action on the feed list, or by changing the approval status on a feed), you get a "500 page unavailable error".

I saw the problem with the timonweb.com/categories/python-and-django feed.

**Comment by timgraham** [comment] 2015-03-26 11:10
Duplicate of https://github.com/django/djangoproject.com/issues/311.

**Closed by timgraham** 2015-03-26 11:10 UTC

**Comment by timonweb** [comment] 2015-04-20 12:02
Hi guys, what's the status of the ticket? Just wondering because I guess my feed is still in the queue. I'd be glad to help to fix this one...

**Comment by timgraham** [comment] 2015-04-20 17:58
Its status is tracked on the duplicate ticket. I just left an update there.
