### ISSUE TITLE
Translated docs no longer built

### ISSUE THREAD

**Issue by claudep** [django/djangoproject.com#997] opened 2020-05-21 08:37 UTC
I discovered that the translated documentations are not built any longer, at least for one month now.

You can check that typically by comparing:
https://docs.djangoproject.com/en/3.0/topics/security/
https://docs.djangoproject.com/fr/3.0/topics/security/
The last sentence about security topics in Mozilla (Django commit 060d9d4229c on 2020-04-22) is not present in the French docs.

**Comment by felixxm** [comment] 2020-05-21 10:16
This is caused by https://github.com/django/django/commit/1cdfe8d91215eefaa18c398069dd9c6879a9511d, because we have mismatched backticks in translations, e.g.
```
Default role used (`single backticks`) at line 1: `UpperCase``. Did you mean to use two backticks for ``code``, or miss an underscore for a `link`_ ?
Default role used (`single backticks`) at line 1: `lhs``. Did you mean to use two backticks for ``code``, or miss an underscore for a `link`_ ?
```
We should change this to a warning.

**Comment by claudep** [comment] 2020-05-21 10:40
Many thanks Mariusz for the debug! I'll still try to fix the offending translation(s).

**Comment by claudep** [comment] 2020-05-21 10:49
@felixxm Do you have a full log of those errors?

**Comment by felixxm** [comment] 2020-05-21 10:59
Sent.

**Comment by claudep** [comment] 2020-05-21 13:09
Thanks, I just pushed a translation update with many fixes, but very difficult to say if all are solved (I admit I didn't run the build locally).

I guess that changing the error to warning will partially ruin the intended effect of catching those errors in the original docs in the CI, but on the other side, it's too much effort to ensure that translations are clean in this regard.

**Comment by felixxm** [comment] 2020-05-21 21:26
I found few more:
```
translations/zh_Hans/LC_MESSAGES/howto.po:"``REMOTE_USER`` 在所有认证请求中都存在。这个假设在当通过 `htpasswd`` 或者相似"
translations/id/LC_MESSAGES/howto.po:"Kami menentukan sebuab perubahan `UpperCase`` yang menggunakan fungsi SQL "
translations/id/LC_MESSAGES/howto.po:"Jika anda mendapatkan sebuah `UnicodeEncodeError`` ketika mengunggah berkas-"
translations/id/LC_MESSAGES/howto.po:"Jika `operasi `RunPython`` atau ``RunSQL`` anda hanya berpengaruh pada satu "
translations/id/LC_MESSAGES/topics.po:"Bayangkan kami mempunyai sebuah bidang ``last_accessed`` di model `Author`` "
translations/el/LC_MESSAGES/howto.po:"χρησιμοποιεί την αρχική τιμή του `lhs`` (το ``self.lhs`` είναι η τιμή μετά 
```
It looks that fixed versions are not "reviewed" in Transifex.

I will try to fix backticks check in the next week.

**Comment by claudep** [comment] 2020-05-22 07:40
I fixed some more. Note that the `reviewed` state on Transifex has no effect on fetched translations, we are fetching all translated strings.

**Comment by felixxm** [comment] 2020-05-22 19:04
Thanks :+1:

**Comment by claudep** [comment] 2020-05-27 11:49
Did you see more errors preventing the build recently?

**Comment by felixxm** [comment] 2020-05-27 18:33
Yes:
```
translations/id/LC_MESSAGES/howto.po:"cara `__init__()`` dari :class:`~django.db.models.Field` (atau kelas induk "
translations/fr/LC_MESSAGES/releases.po:"Épuisement de mémoire dans `django.utils.numberformat.format()``. "
translations/fr/LC_MESSAGES/topics.po:msgstr "Ne pas abuser de  `count()`` et ``exists()``"
translations/fr/LC_MESSAGES/topics.po:"``QuerySet`` Django ou tout autre objet possédant une méthode `count()`` ou "
translations/fr/LC_MESSAGES/topics.po:"différents de `django.conf.global_settings``, vous pouvez transmettre un "
translations/fr/LC_MESSAGES/topics.po:"comportement précédent de `allow_database_queries = True`` peut être obtenu "
translations/fr/LC_MESSAGES/internals.po:"choix en utilisant `oracle.txt``, ``mysql.txt`` ou ``postgres.txt``."
translations/fr/LC_MESSAGES/internals.po:"dire un symbole d'invite ``'$'``, `'/'`` comme séparateur de chemins de "
translations/fr/LC_MESSAGES/intro.po:"Modifiez maintenant la partie suivante du gabarit `polls/index.html`` :"
translations/fr/LC_MESSAGES/ref.po:"dans le modèle lié  `<étiquette_app>.<modèle>``."
translations/fr/LC_MESSAGES/ref.po:"``date_list``. Elle ne peut contenir que `'year'`` (année, par défaut), "
translations/fr/LC_MESSAGES/ref.po:"exemple, `Area(sq_m=2)`` crée un objet :class:`Area` représentant deux "
translations/fr/LC_MESSAGES/ref.po:"exemple, si quelqu'un visite `https://example.com/page.html``, l'en-tête "
translations/fr/LC_MESSAGES/ref.po:"La transmission de `Value(None)`` à ``expression1`` est interdite avec "
translations/fr/LC_MESSAGES/ref.po:"vaut ``DateTimeField()``, `TimeField()`` ou ``DateField()``. Elle renvoie "
translations/es/LC_MESSAGES/internals.po:":doc: `Informe de errores <bugs-and-features> `` en nuestro rastreador de "
translations/es/LC_MESSAGES/intro.po:"Digamos que se encontró la plantilla `news/year_archive.html``. Así es como "
translations/es/LC_MESSAGES/intro.po:"Al registrar el modelo ``Question`` con `admin.site.register (Question)``, "
translations/id/LC_MESSAGES/ref.po:"Metode `clean_<fieldname>()`` dipanggil di sebuah formulir subkelas -- "
translations/id/LC_MESSAGES/ref.po:"depan, bahkan pada Windows (misalnya `C:/homes/user/mysite/sqlite3.db``)."
translations/id/LC_MESSAGES/ref.po:"pemeriksaan (yaitu `[\"models.W001\"]``) yang anda harapkan secara tetap "
translations/ja/LC_MESSAGES/topics.po:"これは2つのことをします。HTML の ``<input>`` に `maxlength=\"100\"`` を配置し"
translations/ko/LC_MESSAGES/intro.po:"Django는 `'toast'``\\를 반환하는 함수 ``django.shortcuts.make_toast()``\\를 "
translations/ko/LC_MESSAGES/intro.po:"토리 안에 있는 `admin/base_site.html`` 템플릿을 방금 만든 디렉토리로 복사합니"
translations/pt_BR/LC_MESSAGES/releases.po:"Para mais informações sobre` `django.newforms``, leia a documentação :doc:"
translations/pt_BR/LC_MESSAGES/howto.po:"``.filter(myfield__mylookup)`` irá chamar `myfield.get_lookup('mylookup')``."
translations/pt_BR/LC_MESSAGES/topics.po:"definie `abstract=False``. Isso significa que filhos de uma classe abstrata "
translations/pt_BR/LC_MESSAGES/topics.po:"Django crie um arquivo cujo o nome seja algo como `/tmp/tmpzfp6I6.upload``. "
translations/pt_BR/LC_MESSAGES/internals.po:"comando `git clean -dfx``."
translations/pt_BR/LC_MESSAGES/intro.po:"Nomeie esse diretório de `django-polls``."
translations/pt_BR/LC_MESSAGES/intro.po:"Substitua a linha `àdmin.site.register(Question)`` por:"
```
but we probably have more of them :disappointed:

**Comment by claudep** [comment] 2020-05-27 18:56
Argh... is the plan still to convert the backtick check to a warning?

**Comment by felixxm** [comment] 2020-05-27 19:07
Yes, it's on my list.

**Comment by felixxm** [comment] 2020-06-03 09:46
Fixed in https://github.com/django/django/commit/36a2e9607e3069e875eedfd814d4473d9b6811cb.

**Closed by felixxm** 2020-06-03 09:46 UTC

**Comment by claudep** [comment] 2020-06-03 11:39
Awesome :+1:

**Comment by claudep** [comment] 2020-08-15 16:58
Looks like this has come again :-( See for example https://docs.djangoproject.com/fr/3.1/topics/db/, all is in English currently.

**Comment by felixxm** [comment] 2020-08-17 08:39
This is sth different, we still have many warnings about backticks but other translations build properly :thinking: This page is in English only for `el`, `es`, and `fr`. Also other pages for `fr` are translated. I will try to figure it out :detective:

**Comment by felixxm** [comment] 2020-08-17 10:33
I manually rebuilt French docs and it works now.

**Comment by claudep** [comment] 2020-08-17 10:35
Thanks a lot! Of course, it would be nice to know what's happening when it fails.

**Comment by felixxm** [comment] 2020-08-17 10:42
I think that rebuilding docs for all translations takes now more than an hour and it overlaps. I will try to add a lock in the next few days.
