### ISSUE TITLE
Text Overflow in the Documentation in Mobile View

### ISSUE THREAD

**Issue by Tushar-sahani** [django/djangoproject.com#1350] opened 2023-04-18 18:55 UTC
### Issue

The Text get Overflow on the website in mobile view looks extremely annoying , cause bad User Experience and breaking the focus while reading the Documentation. The Text overflow should fixed so that it doesn't spoil the user's experience and doesn't break the focus of user, while reading the Documentation.

### Video & Screenshots

![Screenshot_2023-04-18_22_59_41](https://user-images.githubusercontent.com/104075614/232857602-6f95154b-616c-4572-99d2-cfc326c70409.png)
![Screenshot_2023-04-18_23_00_25](https://user-images.githubusercontent.com/104075614/232857615-067910b1-d2f0-4e45-913e-66ec52bc1fb9.png)

### Mobile View

https://user-images.githubusercontent.com/104075614/232856179-0648ffc0-0d24-4bce-af41-5e9c3d9cfd9f.mp4

### Proposed Fix

For avoiding the overflow of text , ```overflow-wrap: break-word``` can be added to the CSS it will break the word if overflow the container. Just adding the overflow-wrap in tag  ```span.pre``` and ```tt``` in ```djangoproject\scss\_style.scss``` would fix the issue. The best way is just added the overflow-wrap property in ```body``` will also fix this problem.

### Screenshot ( After Fixing )

![Screenshot1](https://user-images.githubusercontent.com/104075614/232873912-75d57937-858e-4bf3-bb2a-a15727d46708.png)
![Screenshot2](https://user-images.githubusercontent.com/104075614/232873932-c8cec21f-f9e3-4015-a916-77f8526b9350.png)

**Comment by sabderemane** [comment] 2023-04-19 18:09
Note for @django/djangoproject-com-maintainters : duplicate of #729 

@Tushar-sahani feel free to create a PR for the fix :)

**Comment by vidit-od** [comment] 2023-05-02 12:53
hello community, 
I feel like the three buttons: 'getting help', 'documentation version' and 'language' take up a lot of space in smaller mobile views. 

a combined button with a dropdown list could be implemented to increase the page's visibility.

**Comment by sabderemane** [comment] 2023-05-11 11:51
Closing this since it's a duplicate of #729

**Closed by sabderemane** 2023-05-11 11:51 UTC
