### ISSUE TITLE
Activate your djangoproject.com account

### ISSUE THREAD

**Issue by kennedimalheiros** [django/djangoproject.com#654] opened 2016-04-06 19:59 UTC
When creating my account, I received a link to the following address

To activate this account, please click the following link within the next 3 days:

www.djangoproject.comhttps://www.djangoproject.com/accounts/activate/d31e953e34599b7f1a7a33e4e0a4571bf30df0d4/

The same should contain only this address.

www.djangoproject.com/accounts/activate/d31e953e34599b7f1a7a33e4e0a4571bf30df0d4/

**Comment by timgraham** [comment] 2016-04-07 00:45
Duplicate of https://github.com/django/djangoproject.com/issues/647

**Closed by timgraham** 2016-04-07 00:45 UTC
