### ISSUE TITLE
Popup not always displayed when clicking the stripe pay link

### ISSUE THREAD

**Issue by stenius** [django/djangoproject.com#523] opened 2015-09-10 15:30 UTC
On the fundraising page, instead of displaying a dialog to get information about the user, taken to a blank page instead with the following url:

https://www.djangoproject.com/fundraising/donate/?csrfmiddlewaretoken=6O5yfMNiONVxm9bm85gO676vjiO6cD1t&interval=monthly&amount=50&campaign=1

I noticed this a couple times and was able to reproduce it, but it also seems like it has something to do with Internet connectivity.  Tested on Linux Chrome&FF and an iPad.

**Comment by olasitarska** [comment] 2015-09-10 15:39
Thanks @stenius, I'll try reproducing that. Do you think this may have something to do with the fact that Stripe Checkout JavaScript hasn't fully loaded in your browser before you hit the button? This could be explained by internet connectivity.

**Comment by stenius** [comment] 2015-09-10 15:43
I think so.  I can't reproduce it anymore after I've got it working but if I'm quick in a new incognito window I can make it fail.

**Comment by timgraham** [comment] 2015-11-21 22:09
I deployed lazy loading of funders images on that page 47e5cbbe7f204680917fd0bf2582b140e37fe2bb. I can't reproduce this in an incognito window (clicking the "Donate" link as soon as possible), but I didn't try before rolling out the change either. Can you still reproduce it?

**Comment by timgraham** [comment] 2015-11-30 22:45
Closing in absence of follow up and "worksforme".

**Closed by timgraham** 2015-11-30 22:45 UTC
