### ISSUE TITLE
Migration: Rename model does not rename all tables of the model in postgresql.

### ISSUE THREAD

**Issue by jarifibrahim** [django/djangoproject.com#725] opened 2016-12-06 05:24 UTC
I have a migration that renames the following model 
```
class ConsultantSurvey(models.Model):
    team = models.ForeignKey(Team, related_name="consultant_surveys")
    missing_member = models.ManyToManyField(Member,
                                            related_name="surveys",
                                            blank=True)
    ...
```
and its `migration 0019` as 
```
class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20161204_0054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FellowSurvey',
            new_name='ConsultantSurvey',
        ),
    ]
```
Migration `0018` is 
```
class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20161129_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowSurvey',
            fields= ...
        ),
      ....
       migrations.AddField(
                model_name='fellowsurvey',
                name='missing_member',
                field=models.ManyToManyField(blank=True, related_name='surveys', to='dashboard.Member'),
            )
]
```

The migration runs perfectly fine on `sqlite3` database but fails on `postgresql`.
I tried running migration `0018` and then `0019`. 
This is what I found. 
On running `0018` on `postgresql` the following tables were created
![screenshot from 2016-12-06 10-47-34](https://cloud.githubusercontent.com/assets/12949454/20913906/84e57f30-bba1-11e6-99a4-b17e0dac637a.png)

and on running `0019` only two tables were renamed out of the four for the `FellowSurvey`.

![screenshot from 2016-12-06 10-49-00](https://cloud.githubusercontent.com/assets/12949454/20913940/b72744ec-bba1-11e6-8051-2a906c661e9b.png)

The migrations now fail as I have another model with the name `FellowSurvey`. The process should have been 
1. `Create` model `FellowSurvey`
2. `Rename` model `FellowSurvey` to `ConsultantSurvey` 
3. `Create` model `FellowSurvey`

All the migrations I have can be found here https://github.com/jarifibrahim/ashoka-dashboard/tree/f1eadb9c9327432a717255f1a3e1dd012471207e/dashboard/migrations

**Comment by timgraham** [comment] 2016-12-06 12:33
Hi, this is the bug tracker for djangoproject.com. Please use code.djangoproject.com for bugs in Django. This looks like a duplicate of [#23577](https://code.djangoproject.com/ticket/23577).

**Closed by timgraham** 2016-12-06 12:33 UTC
