### ISSUE TITLE
Small font size under Chromium Debian 64-bit

### ISSUE THREAD

**Issue by stefanos82** [django/djangoproject.com#765] opened 2017-05-07 23:38 UTC
To whom it may concern,

[Official docs](https://docs.djangoproject.com/en/1.11/) fonts size are way too small under Chromium 58.0.3029.81 on GNU / Linux Debian testing 64-bit.

The same link has been tested with Firefox and the fonts size is large and enjoyable.

I don't remember this kind of behavior in the past.

Is there anything I should check?

Cheers.

**Comment by timgraham** [comment] 2017-05-07 23:42
Any chance you have your browser zoomed out? I can't reproduce the issue.

**Comment by stefanos82** [comment] 2017-05-07 23:55
No, my view is at 100%. 

The following user from official IRC channel reproduced it and reported back the problem:

```text
<hailhydra> yeah body {font-size} isn't inheriting 1.8ems its getting #docs-content { font-size: 1.4ems}
```

**Comment by timgraham** [comment] 2017-05-08 00:28
Is it a browser bug?

**Comment by stefanos82** [comment] 2017-05-08 05:22
I wish I knew `¯\_(ツ)_/¯`, I never had this issue before.

**Comment by stefanos82** [comment] 2017-05-12 10:05
@timgraham so it seems both browsers behave differently for django docs.

For example, https://docs.djangoproject.com/en/1.11/intro/tutorial05/#testing-our-new-view `polls/tests.py` breaks indentation under Firefox, whereas on Chromium is shown just fine, but with smaller fonts of course.

What should be the golden ratio in this case so both browsers if not all of them produce the same documentation output?

**Comment by timgraham** [comment] 2017-05-12 11:28
I don't have time to look into this now.

**Comment by stefanos82** [comment] 2017-05-12 11:31
No worries, whenever you feel like doing so.

**Comment by timgraham** [comment] 2017-05-12 12:15
The font size looks fine to me on Chromium 58.0.3029.96 Built on Ubuntu, running on Ubuntu 14.04 (64-bit).

**Comment by stefanos82** [comment] 2017-05-12 12:26
Here's the font size in `58.0.3029.81 (Developer Build) built on Debian 9.0, running on Debian 9.0 (64-bit)`:

![chromium-tutorial05](https://cloud.githubusercontent.com/assets/1777466/25997886/07177b6a-3727-11e7-810b-4917a02f3acc.png)

Here's the font size in `Firefox 45.9.0`:

![firefox-tutorial05](https://cloud.githubusercontent.com/assets/1777466/25997913/385a060c-3727-11e7-8b31-f1a4748308e5.png)

And finally, here's the indentation issue under Firefox that font size causes:

![firefox-tutorial05-indentation-issue](https://cloud.githubusercontent.com/assets/1777466/25997939/53189bca-3727-11e7-8842-cd2419c235b2.png)

If I reduce the zoom size, indentation issue goes away.

**Comment by timgraham** [comment] 2017-05-12 12:32
I guess the next step is to see if anyone else can reproduce the font size issue since I cannot.

The indentation issue is discussed in https://github.com/django/djangoproject.com/issues/662.

**Comment by stefanos82** [comment] 2017-05-12 12:38
I will test this on Windows 7 to see whether the issue is reproducible there as well.

**Comment by stefanos82** [comment] 2017-05-12 12:52
OK, on `Windows 7` all three browsers of mine, that is `Internet Explorer 11`, `Chrome 58.0.3029.110 (Official Build) (64-bit)`, and `Firefox 53.0.2 (64-bit)` behave as expected.

So, I guess it has something to do with the fonts Debian is using / choosing? I haven't done anything on any browser I use under `Debian testing 64-bit`.

**Comment by timgraham** [comment] 2017-05-12 12:54
Not sure, possibly @claudep has some knowledge about that.

**Comment by claudep** [comment] 2017-05-12 13:39
What's essential is to tell us which real font is in use at which size. This can be discovered by using the  Developer Tools (F12), inspecting one of the paragraphs, activating the "Computed" tab on the right and looking at the listed properties. Also look at "Rendered Fonts" section below the properties.

I cannot reproduce this issue on my two Debian (8 and 9) systems, sorry.

**Comment by stefanos82** [comment] 2017-05-12 13:47
Firefox results:

```css
font-family: "Roboto",Corbel,Avenir,"Lucida Grande","Lucida Sans",sans-serif;
: output.979a53253070.css:4;
: #docs-content"Roboto",Corbel,Avenir,"Lucida Grande","Lucida Sans",sans-serif;
: output.979a53253070.css:4;
: bodyPalatino,"Palatino Linotype","Book Antiqua","Hoefler Text",Georgia,"Lucida Bright",Cambria,Times,"Times New Roman",serif;
: output.979a53253070.css:1;
: htmlsans-serif;
```

Chromium results:

```css
"Roboto", Corbel, Avenir, "Lucida Grande", "Lucida Sans", sans-serifoutput.979a53253070.css:4#docs-content
Palatino, "Palatino Linotype", "Book Antiqua", "Hoefler Text", Georgia, "Lucida Bright", Cambria, Times, "Times New Roman", serifoutput.979a53253070.css:4body
sans-serifoutput.979a53253070.css:1html
```

**Comment by timgraham** [comment] 2017-11-14 16:19
Feel free to send a patch if you find a solution. Closing for now since no one else is able to reproduce.

**Closed by timgraham** 2017-11-14 16:19 UTC
