### ISSUE TITLE
Broken Debug Toolbar for docs

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#796] opened 2017-11-09 18:23 UTC
Django Debug Toolbar works well for `www` , for example, if I open http://www.djangoproject.dev:8000/ I can show the toolbar and open the SQL panel.

If I try to open for example http://docs.djangoproject.dev:8000/en/1.11/ I can see the toolbar but I got `0: error` if I try to open SQL panel

This is the message I saw on browser console:
`Failed to load http://www.djangoproject.dev:8000/__debug__/render_panel/?store_id=212b2bb5adc54a3a81b97b6da5547d4c&panel_id=SQLPanel: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://docs.djangoproject.dev:8000' is therefore not allowed access.`

If i open the url http://www.djangoproject.dev:8000/__debug__/render_panel/?store_id=212b2bb5adc54a3a81b97b6da5547d4c&panel_id=SQLPanel I can see all the data

I think the problem is the toolbar is trying to open a www. for the panel instead of a doc. url but I don't know how to update the settings to fix this.

**Comment by pauloxnet** [comment] 2017-11-23 08:20
@timgraham have you ever tried to use debug-toolbar locally in docs sections ?
Fixing this bug can help us to speed-up this query-intensive section.

**Comment by timgraham** [comment] 2017-11-23 13:56
I briefly looked at this issue and could reproduce it but I'm not sure how to solve it.

**Comment by pauloxnet** [comment] 2017-11-23 14:21
Are there any **django-debug-toolbar** experts who can help us solve this bug ?
I see, for example, @aaugustin and @jezdez among the contributors to this project.

**Comment by aaugustin** [comment] 2017-11-25 12:38
*former contributors

**Comment by pauloxnet** [comment] 2017-11-29 08:48
I added a question on StackOverflow about this bug, can you upvote it so many user can see it and help us to solve this issue ?
https://stackoverflow.com/questions/47548490/broken-django-debug-toolbar-panels-with-sub-domains-configuration

**Comment by jezdez** [comment] 2017-11-29 09:23
Ugh, I wish you hadn't posted on Stackoverflow. In short: this is a CORS error since it tries to request a resource with Javascript on a different subdomain that isn't allowed to be requested.

The reason why the URL that is [rendered by debug_toolbar](https://github.com/jazzband/django-debug-toolbar/blob/36d3c039ea8bb6b989e9136b623fee0ad770caff/debug_toolbar/templates/debug_toolbar/base.html#L16) uses the `www` subdomain automatically is because the djangoproject project has django-hosts [hosts_override](http://django-hosts.readthedocs.io/en/latest/templatetags.html#override-the-default-url-template-tag) feature [installed](https://github.com/django/djangoproject.com/blob/4424902f55655fad583b6b178ad67cae33c83bac/djangoproject/settings/common.py#L196-L198), which automatically overrides the Django-built-in url template tag witht he one that is capable of resolving Django URLs as a fully qualified URL and not only as URL paths.

The `host_url` template tag which is by now also called when the `url` template tag is used, will [fall back](https://github.com/jazzband/django-hosts/blob/master/django_hosts/templatetags/hosts.py#L144-L147) to using the host as defined by the `DEFAULT_HOST` setting, which in our case is [`www`](https://github.com/django/djangoproject.com/blob/4424902f55655fad583b6b178ad67cae33c83bac/djangoproject/settings/common.py#L229).

Since we can't easily override the call to the `url` tag in the debug toolbar template to pass in a different host (e.g. `docs`) there is basically only one other option: set the appropriate CORS header `Access-Control-Allow-Origin` to allow a page loaded under the `docs` subdomain to access a resource under the `www` subdomain. I would strongly suggest to do that and not mess with the URL generation. That said, this is something that should only be applied to the development environment, to reduce the chance for abuse in production.

Actually setting the CORS header is as simple as writing a very small middleware that does it manually. No need to use a full-blown app like django-cors-headers.

**Comment by pauloxnet** [comment] 2017-11-29 09:31
Thanks, the first result of my post on stackoverflow is your answer ;-)

I'll try to find the time to write this CORS middleware and then send a PR to @timgraham 

If you want, add your answer to stackoverflow, otherwise I'll do it after PR merge.

**Comment by pauloxnet** [comment] 2017-12-06 08:12
I tested locally the middleware suggested by @jezdez and it works.
I commented the middleware as requested by @timgraham

**Closed** 2017-12-26 23:42 UTC
