### ISSUE TITLE
Community page not updating feeds

### ISSUE THREAD

**Issue by vindio** [django/djangoproject.com#1270] opened 2022-11-16 17:50 UTC
There seems to be an issue fetching and displaying feeds in [Django Community](https://www.djangoproject.com/community/)

Django links, Django Q&A, New/Updated Django Packages, Django Jobs and Community blog posts are not properly updating its contents. Displayed items are from 2009 and 2011.

Ordering is also broken. Section headers are repeated with only a few items each time instead of displaying every section header once with all it's items.

**Comment by youker-Shawn** [comment] 2022-11-17 05:13
This has been happening for about 2 weeks.

**Comment by carltongibson** [comment] 2022-11-17 09:33
@CuriousLearner There are up to date `FeedItems` in the DB. (e.g. latest date modified Nov. 17, 2022, 9:21 a.m.) 

> This has been happening for about 2 weeks.

https://github.com/django/djangoproject.com/commits/main/aggregator — There's the changes from @saadmk11, but I don't spot an obvious regression there 🤔

Could it be related to #1137? (That's about adding new feeds rather than feed items, but we need a replacement story there...)

**Comment by CuriousLearner** [comment] 2022-11-17 10:15
I think the ordering is coming from the model itself rather than the view, so there isn't a regression there, but let me check the other thread to see if I've any ideas.

**Comment by saadmk11** [comment] 2022-11-17 10:42
Looks like https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#grouping-on-other-properties does not work for a double foreign key relation (`feeditem.feed.feed_type`). That's why we are getting duplicates. Locally I was using a small number of items and one feed for each type so I did not see this issue.  Probably best to revert the changes made here: https://github.com/django/djangoproject.com/pull/1262

https://github.com/django/djangoproject.com/blob/990c548806ed0f3bf9ea8c6fbb032048efecec04/djangoproject/templates/aggregator/index.html#L16

**Comment by carltongibson** [comment] 2022-11-17 10:44
> Probably best to revert the changes made here: https://github.com/django/djangoproject.com/pull/1262

@saadmk11 Good work. Can you make that PR? 

(Can the original issue be fixed with an appropriate prefetch...? 🤔)

**Comment by saadmk11** [comment] 2022-11-17 12:01
> > Probably best to revert the changes made here: #1262
> 
> @saadmk11 Good work. Can you make that PR?
> 
@carltongibson Created a PR https://github.com/django/djangoproject.com/pull/1273

> (Can the original issue be fixed with an appropriate prefetch...? thinking)

We can do something like this:

```python
from collections import defaultdict

from django.db.models import Prefetch
from pprint import pprint

from aggregator.models import APPROVED_FEED, FeedItem, FeedType

qs = FeedType.objects.all().prefetch_related(
    Prefetch(
        'feed_set__feeditem_set',
        queryset=FeedItem.objects.filter(feed__approval_status=APPROVED_FEED),
        to_attr='feed_items',
    )
)

items = defaultdict(list)

for feed_type in qs:
    for feed in feed_type.feed_set.all():
        items[feed_type].extend(feed.feed_items)
```

But that causes an issue with fetching all the items in memory (not a  problem if there are handful of feed items) and we only need `5` per category. I am not aware of a way to prefetch using a slice (maybe possible with a SubQuery?)

**Comment by carltongibson** [comment] 2022-11-17 12:54
@saadmk11 — Let's look at it in a fresh PR if we can please. Test cases using `assertNumQueries` like you added in ff6c87a3bf54df7bf8f504c36e82a27f2cf1c6c7  will tell us what we need to know. Thanks!

**Closed** 2022-11-17 12:58 UTC

**Comment by carltongibson** [comment] 2022-11-17 13:31
Looks more like it... 

<img width="754" alt="Screenshot 2022-11-17 at 14 30 45" src="https://user-images.githubusercontent.com/64686/202459562-98d722a0-b5f1-4a8c-af99-a6a6ba644705.png">


Thanks all!
