### ISSUE TITLE
Sitemap is broken

### ISSUE THREAD

**Issue by aaugustin** [django/djangoproject.com#535] opened 2015-10-09 11:46 UTC
https://docs.djangoproject.com/sitemap.xml shows bad URLs e.g.

    <url>
        <loc>https://www.djangoproject.comhttps://docs.djangoproject.com/en/dev/./</loc>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>

**Comment by timgraham** [comment] 2015-11-16 19:39
Pull request: https://github.com/django/djangoproject.com/pull/544 (needs tests)

**Comment by timgraham** [comment] 2015-11-30 22:46
Duplicate of https://github.com/django/djangoproject.com/issues/472.

**Closed by timgraham** 2015-11-30 22:46 UTC
